#!/usr/bin/env python3
# Copyright 2026 Lusoris
# SPDX-License-Identifier: EUPL-1.2
"""Render docs/hardware-reports/index.md from the tracked reports (ADR-0173, #233).

    generate-index.py --check        exit 1 when index.md differs from the rendering
    generate-index.py --write        rewrite index.md
    generate-index.py --self-test [--disable RULE]

An empty credit is shown as `anonymous`. Reports are validated by check-reports.py;
this script reads them as given and fails on a file it cannot render.
"""

import argparse
import importlib.util
import json
import sys
import tempfile
from pathlib import Path

HERE = Path(__file__).resolve().parent
RULES = ("index_row", "index_stale_check", "credit_anonymous")


def load_checker():
    spec = importlib.util.spec_from_file_location("check_reports", HERE / "check-reports.py")
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


CHECK = load_checker()
DIR = CHECK.DIR

HEADER = """\
<!-- markdownlint-disable MD013 -->
<!-- GENERATED by scripts/hardware-reports/generate-index.py from the report files
in this directory; do not edit by hand. Add a report file and run
`python3 -I scripts/hardware-reports/generate-index.py --write`. -->

# Hardware reports

Reports from the [tester kit](../development/tester.md) on machines outside the
project, one file per report. Each row links the file. A report with verdict
`fail` is welcome: it is a finding. Rules for a file and what the columns mean:
[hardware we need](../usage/hardware-we-need.md#send-a-report). The record format
is [`intake.schema.json`](intake.schema.json).

"""
TABLE = """\
| Date | Machine | Devices | Class | Claim | Verdict | Source commit | Credit | Report |
| --- | --- | --- | --- | --- | --- | --- | --- | --- |
"""
EMPTY = "No reports have been submitted yet.\n"


def cell(text):
    """Make free text safe for one table cell."""
    flat = " ".join(str(text).split())
    for ch, sub in (("|", "/"), ("<", ""), (">", ""), ("`", "'")):
        flat = flat.replace(ch, sub)
    return flat or "-"


def row(path, disabled):
    env = json.loads(path.read_text(encoding="utf-8"))
    rep = env["report"]
    devices = ", ".join(d["name"] for d in rep["devices"])
    cells = [rep["generated_utc"][:10], cell(env.get("machine", "")), cell(devices),
             rep["execution_class"], rep["evidence_claim"], rep["verdict"],
             "`%s`" % rep["commit"][:12], cell(CHECK.credit_display(env, disabled)),
             "[%s](%s)" % (path.name, path.name)]
    return "| " + " | ".join(cells) + " |"


def render(directory, disabled=frozenset()):
    paths = CHECK.report_files(directory)
    if not paths or "index_row" in disabled:
        return HEADER + EMPTY
    return HEADER + TABLE + "\n".join(row(p, disabled) for p in paths) + "\n"


def index_stale(directory, disabled=frozenset()):
    """True when index.md is missing or differs from the rendering."""
    if "index_stale_check" in disabled:
        return False
    out = Path(directory) / "index.md"
    return not out.is_file() or out.read_text(encoding="utf-8") != render(directory)


def self_test(disabled):
    failures = []
    with tempfile.TemporaryDirectory(prefix="pelorus-index-") as tmp:
        tmpdir = Path(tmp)
        for name, env in CHECK.planted_reports():
            if name == "anonymous_empty_credit":
                (tmpdir / "2026-01-01-anon.json").write_text(json.dumps(env), encoding="utf-8")
        text = render(tmpdir, disabled)
        if "2026-01-01-anon.json" not in text:
            failures.append("valid_report_in_index")
        if "| anonymous |" not in text:
            failures.append("empty_credit_anonymous_in_index")
        (tmpdir / "index.md").write_text(HEADER + EMPTY, encoding="utf-8")
        if not index_stale(tmpdir, disabled):
            failures.append("stale_index_detected")
        (tmpdir / "index.md").write_text(render(tmpdir), encoding="utf-8")
        if index_stale(tmpdir, disabled):
            failures.append("fresh_index_accepted")
    for line in failures:
        print("SELF-TEST FAIL: " + line, file=sys.stderr)
    print("self-test: %s" % ("FAILED (%d)" % len(failures) if failures else "ok"))
    return 1 if failures else 0


def main(argv):
    top = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    top.add_argument("--dir", default=str(DIR))
    mode = top.add_mutually_exclusive_group(required=True)
    mode.add_argument("--check", action="store_true")
    mode.add_argument("--write", action="store_true")
    mode.add_argument("--self-test", action="store_true", dest="self_test")
    top.add_argument("--disable", action="append", choices=RULES, default=[])
    args = top.parse_args(argv)
    if args.self_test:
        return self_test(frozenset(args.disable))
    if args.write:
        (Path(args.dir) / "index.md").write_text(render(args.dir), encoding="utf-8")
        return 0
    if index_stale(args.dir):
        print("error: %s/index.md is stale; run generate-index.py --write" % args.dir,
              file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
