#!/usr/bin/env bash
#
# concat-changelog-fragments.sh — render CHANGELOG.md's [Unreleased] block from
# the changelog.d/ fragments (Keep-a-Changelog). See changelog.d/README.md and
# ADR-0108. The block between the BEGIN/END UNRELEASED markers in CHANGELOG.md is
# generated; everything else (header, released sections, link refs) is manual.
#
# Copyright 2026 Lusoris. BSD-2-Clause-Patent.
#
#   concat-changelog-fragments.sh --write   rewrite the block in place
#   concat-changelog-fragments.sh --check   fail if the block is out of date
#
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
CHANGELOG="$ROOT/CHANGELOG.md"
FRAG="$ROOT/changelog.d"
BEGIN='<!-- BEGIN UNRELEASED (generated by scripts/release/concat-changelog-fragments.sh) -->'
END='<!-- END UNRELEASED -->'

SECTIONS=(added changed deprecated removed fixed security)
TITLES=(Added Changed Deprecated Removed Fixed Security)

render() {
    printf '%s\n' "$BEGIN"
    printf '## [Unreleased]\n\n'
    local i had=0
    for i in "${!SECTIONS[@]}"; do
        local dir="$FRAG/${SECTIONS[$i]}"
        [ -d "$dir" ] || continue
        local files
        files=$(find "$dir" -maxdepth 1 -name '*.md' | sort)
        [ -z "$files" ] && continue
        had=1
        printf '### %s\n\n' "${TITLES[$i]}"
        local f
        while IFS= read -r f; do
            cat "$f"
        done <<< "$files"
        printf '\n'
    done
    [ "$had" = 0 ] && printf '_No unreleased changes._\n\n'
    printf '%s\n' "$END"
}

tmp="$(mktemp)"
trap 'rm -f "$tmp"' EXIT

# head = lines before BEGIN; tail = lines after END.
awk -v b="$BEGIN" '{ if ($0==b) exit; print }' "$CHANGELOG" > "$tmp.head"
awk -v e="$END" 'f{print} $0==e{f=1}' "$CHANGELOG" > "$tmp.tail"

{
    cat "$tmp.head"
    render
    cat "$tmp.tail"
} > "$tmp"
rm -f "$tmp.head" "$tmp.tail"

case "${1:---check}" in
    --write)
        mv "$tmp" "$CHANGELOG"
        trap - EXIT
        echo "CHANGELOG.md [Unreleased] block regenerated."
        ;;
    --check)
        if diff -u "$CHANGELOG" "$tmp" >/dev/null; then
            echo "CHANGELOG.md is up to date with changelog.d/."
        else
            echo "CHANGELOG.md is stale — run: scripts/release/concat-changelog-fragments.sh --write" >&2
            diff -u "$CHANGELOG" "$tmp" >&2 || true
            exit 1
        fi
        ;;
    *)
        echo "usage: $0 [--write|--check]" >&2; exit 2 ;;
esac
