#!/usr/bin/env bash
#
# fetch-corpus.sh — materialize the pinned benchmark corpus as raw YUV.
#
# Copyright 2026 Lusoris
# SPDX-License-Identifier: EUPL-1.2
#
# Reads scripts/bench/corpus.lock, downloads each pinned clip (cached + sha256
# verified), and extracts its pinned segment to raw YUV at the pinned
# resolution/format. Output: <corpus-dir>/<name>.yuv (+ a .meta with dims).
# Makes the bench reproducible from a pinned source on any machine.
#
#   FFMPEG=/path/to/ffmpeg CORPUS=.bench-corpus ./fetch-corpus.sh [name...]
#   CORPUS_LOCK=<file> and CURL_MAX_TIME=<seconds, default 600> override the pin list and deadline.
set -euo pipefail

HERE="$(cd "$(dirname "$0")" && pwd)"
ROOT="$(cd "$HERE/../.." && pwd)"
FFMPEG="${FFMPEG:-ffmpeg}"
CORPUS="${CORPUS:-$ROOT/.bench-corpus}"
LOCK="${CORPUS_LOCK:-$HERE/corpus.lock}"
# Per-attempt transfer deadline in seconds (clips are tens of MB).
CURL_MAX_TIME="${CURL_MAX_TIME:-600}"
mkdir -p "$CORPUS"

want=("$@")
want_clip() { [ ${#want[@]} -eq 0 ] && return 0; for w in "${want[@]}"; do [ "$w" = "$1" ] && return 0; done; return 1; }

while IFS='|' read -r name url sha seek scale pixfmt frames fps; do
    # Skip blanks/comments BEFORE xargs: xargs treats quotes as syntax and dies on
    # an apostrophe in a comment ("unmatched single quote"), which made a prose
    # comment in corpus.lock able to break the whole fetch.
    case "$(printf '%s' "$name" | tr -d '[:space:]')" in ''|\#*) continue;; esac
    name="$(echo "$name" | xargs)"
    want_clip "$name" || continue
    url="$(echo "$url" | xargs)"; sha="$(echo "$sha" | xargs)"; seek="$(echo "$seek" | xargs)"
    scale="$(echo "$scale" | xargs)"; pixfmt="$(echo "$pixfmt" | xargs)"
    frames="$(echo "$frames" | xargs)"; fps="$(echo "$fps" | xargs)"
    w="${scale%x*}"; h="${scale#*x}"
    yuv="$CORPUS/$name.yuv"

    echo "== $name (${scale} ${pixfmt} ${frames}f@${fps}) =="
    if [ "$url" = "lavfi:gradients" ]; then
        # Synthetic dark gradient (banding torture). gradients draws a random
        # pattern unless seeded (its seed defaults to -1), so the seed is fixed
        # and the generated bytes are checked against the pinned sha256: two
        # bench runs, or two candidates, must see the same clip.
        [ "$sha" != "-" ] || { echo "  NO SHA PINNED for generated clip $name" >&2; exit 1; }
        tmp_yuv="$(mktemp "$yuv.XXXXXX.part")"
        if ! "$FFMPEG" -hide_banner -loglevel error -y \
            -f lavfi -i "gradients=size=${scale}:x0=0:y0=0:x1=0:y1=${h}:c0=0x060608:c1=0x2a3038:nb_colors=2:rate=${fps}:seed=1" \
            -vf "format=${pixfmt}" -frames:v "$frames" -f rawvideo "$tmp_yuv"; then
            rm -f -- "$tmp_yuv"
            echo "  GENERATION FAILED: $name" >&2
            exit 1
        fi
        got="$(sha256sum "$tmp_yuv" | cut -d' ' -f1)"
        if [ "$got" != "$sha" ]; then
            rm -f -- "$tmp_yuv"
            echo "  SHA MISMATCH for generated clip $name: got $got want $sha ($FFMPEG)" >&2
            exit 1
        fi
        mv -- "$tmp_yuv" "$yuv"
        echo "  sha256 OK (generated)"
    else
        local_dl="$CORPUS/$(basename "$url")"
        if [ ! -f "$local_dl" ] || [ "$(sha256sum "$local_dl" | cut -d' ' -f1)" != "$sha" ]; then
            echo "  downloading $url"
            # Download to a temporary name, verify, then publish: a failed or
            # corrupt transfer must never leave a file where the corpus belongs.
            # --fail turns an HTTP error into a non-zero exit instead of saving
            # the error page; --max-time bounds every attempt (HISS-02).
            tmp_dl="$(mktemp "$local_dl.XXXXXX.part")"
            if ! curl --fail --show-error --silent --location \
                --max-time "$CURL_MAX_TIME" --retry 2 --retry-max-time "$CURL_MAX_TIME" \
                --output "$tmp_dl" -- "$url"; then
                rm -f -- "$tmp_dl"
                echo "  DOWNLOAD FAILED: $url" >&2
                exit 1
            fi
            got="$(sha256sum "$tmp_dl" | cut -d' ' -f1)"
            if [ "$got" != "$sha" ]; then
                rm -f -- "$tmp_dl"
                echo "  SHA MISMATCH: got $got want $sha" >&2
                exit 1
            fi
            mv -- "$tmp_dl" "$local_dl"
        fi
        got="$(sha256sum "$local_dl" | cut -d' ' -f1)"
        [ "$got" = "$sha" ] || { echo "  SHA MISMATCH: got $got want $sha" >&2; exit 1; }
        echo "  sha256 OK; extracting pinned segment $seek -> $yuv"
        # shellcheck disable=SC2086
        "$FFMPEG" -hide_banner -loglevel error -y $seek -i "$local_dl" \
            -vf "scale=${w}:${h}:flags=bicubic,format=${pixfmt}" \
            -frames:v "$frames" -an -f rawvideo "$yuv"
    fi
    printf 'width=%s\nheight=%s\npixfmt=%s\nframes=%s\nfps=%s\n' \
        "$w" "$h" "$pixfmt" "$frames" "$fps" > "$CORPUS/$name.meta"
    echo "  ready: $yuv ($(stat -c%s "$yuv") bytes)"
done < "$LOCK"
